# -*- coding: utf-8 -*-
"""sort_object.py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XWvobnVCc3r0AbGKV5Ah5uFqi3GUmqPt
"""

obj_detected = {'bottle': [110, 30], 'glass': [60, 35], 'book': [310, 23], 'phone': [90, 33], 'dice': [155, 38], 'mouse':[200, 45], 'keyboard': [298, 65], 'fan': [300, 36]}
sorted_obj_detected = sorted(obj_detected.items(), key=lambda x:x[1])
converted_dict = dict(obj_detected)
print(sorted_obj_detected)